# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  REGION:
    sh: echo ${AWS_REGION:-ap-northeast-1}
  PROJECT_NAME:
    sh: echo ${PROJECT_NAME:-coastguard-demo}
  REPO:
    sh: echo ${REPO:-github.com/mackee/coastguard}
  TERRAFORM_BUCKET:
    sh: echo ${TERRAFORM_BUCKET:-coastguard-demo-terraform}
  TERRAFORM_BUCKET_KEY:
    sh: echo ${TERRAFORM_BUCKET_KEY:-coastguard-demo/terraform.tfstate}
  TERRAFORM_BACKEND_CONFIG: -backend-config="bucket={{ .TERRAFORM_BUCKET }}" -backend-config="key={{ .TERRAFORM_BUCKET_KEY }}" -backend-config="region={{ .REGION }}"
  TERRAFORM_ARGS: -var="region={{ .REGION }}" -var="project_name={{ .PROJECT_NAME }}" -var="repo={{ .REPO }}"
tasks:
  generate-private-key:
    desc: Generate RSA key pair for signing
    status:
      - test -f private_key.pem
    cmds:
      - openssl genrsa -out private_key.pem 2048
  generate-public-key:
    desc: Generate public key from private key
    status:
      - test -f public_key.pem
    deps:
      - task: generate-private-key
    cmds:
      - openssl rsa -pubout -in private_key.pem -out public_key.pem
  init:
    desc: Initialize the Terraform configuration
    cmds:
      - terraform init {{ .TERRAFORM_BACKEND_CONFIG }}
  plan:
    desc: Plan the Terraform configuration
    cmds:
      - task: download-lambda
      - terraform plan {{ .TERRAFORM_ARGS }}
      - defer: rm -f coastguard.zip
  apply:
    desc: Apply the Terraform configuration
    cmds:
      - task: download-lambda
      - terraform apply {{ .TERRAFORM_ARGS }}
      - defer: rm -f coastguard.zip
  download-lambda:
    internal: true
    desc: Download the Lambda function binary from GitHub
    vars:
      FILENAME: coastguard_linux_arm64.zip
      VERSION: v0.1.1
      CHECKSUM: 722470b326378966b7d37ad6b0b5f4e2926e42ebaf04cca92aa2cda73b600dd3
    cmds:
      - curl -o coastguard.zip -sL https://github.com/mackee/coastguard/releases/download/{{ .VERSION }}/{{ .FILENAME }}
      - shasum -a 256 coastguard.zip | grep {{ .CHECKSUM }} || (echo "Checksum verification failed" && exit 1)
